name: CI - Lint, Format, and Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-format-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (adjust the version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Cache Node Modules
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Lint with ESLint
      - name: Run ESLint
        run: npm run lint

      # Step 6: Check Code Formatting with Prettier
      - name: Run Prettier
        run: npm run format:check

      # Step 7: Build the React Application
      - name: Build React App
        run: npm run build
