name: ESLint Check

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js (adjust the version if needed)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use a version compatible with your project

      # Step 3: Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npm run lint
